<a href="https://colab.research.google.com/github/Aashrit77/Python/blob/main/Feature_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [2]:
df = pd.read_csv("/content/diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [3]:
array = df.values

In [4]:
x = array[:,0:8]
y = array[:,8]

In [8]:
test = SelectKBest(score_func=chi2,k=4)
fit = test.fit(x,y)
set_printoptions(precision=3)
print(fit.scores_)
#features = fit.transform(x)

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [9]:
features = fit.transform(x)

In [10]:
features

array([[148. ,   0. ,  33.6,  50. ],
       [ 85. ,   0. ,  26.6,  31. ],
       [183. ,   0. ,  23.3,  32. ],
       ...,
       [121. , 112. ,  26.2,  30. ],
       [126. ,   0. ,  30.1,  47. ],
       [ 93. ,   0. ,  30.4,  23. ]])

In [11]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [12]:
model = LogisticRegression(max_iter=400)
rfe = RFE(model,3)
fit = rfe.fit(x,y)

In [13]:
#to view boolean values for the sleected top features we use support
fit.support_

array([ True, False, False, False, False,  True,  True, False])

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
model = DecisionTreeClassifier()
fit = model.fit(x,y)
print(fit.feature_importances_) #this by default gives the gini impurity and the higest value feature will help us reduce the gini impurity

[0.061 0.321 0.103 0.015 0.045 0.207 0.138 0.111]
